### ISSUE TITLE
Transaction name multiplies when upgrading to v10 with ESM

### ISSUE THREAD

**Issue by Marcholio** [newrelic/node-newrelic#1646]
## Description

After updating agent from 9.15.0 to 10.1.1 transaction names have started to multiply paths, for example POST `/api` is reported as `POST /api/api/api/api/api/api/api/api`.

See screenshot:
![Screenshot 2023-05-22 at 15 58 34](https://github.com/newrelic/node-newrelic/assets/15167296/6cef902d-ecf6-48d2-b15a-7af1aef32224)

## Expected Behavior

Transaction name should be reported as previously.

## Steps to Reproduce

- Setup basic express app
- install agent 9.15.0 with default config
- Monitor transactions
- Update agent to 10.1.1
- Monitor transactions and see that names are multiplying

## Your Environment

- Express 4.18.0
- Node.js 18.15.0
- Newrelic agent 10.1.1

## Additional context
We are using newrelic ESM loader for ESM codebase.

**Comment by jmartin4563** [comment]
@Marcholio I booted up a quick example app using agent version 10.1.1 (which you can see [here](https://github.com/jmartin4563/express-esm-app)), and I'm not seeing the behavior your screenshot shows. Could you describe more about how your express app is set up and what it does so I can try and get a good repro case? Additionally, which UI screen is that screenshot you posted from, is it `Transactions` or `Distributed Tracing`?

**Comment by Marcholio** [comment]
@jmartin4563 Screenshot is from `Transactions`. I think this is not an issue with v10 itself, but most likely with ESM loader, because we have other apps using v10 that do not have the same problem. I'll see if I can come up with a repro case.

**Comment by jmartin4563** [comment]
@Marcholio I'm also using the ESM loader in that example app, where I provide `--experimental-loader` in my `start` [npm script](https://github.com/jmartin4563/express-esm-app/blob/main/package.json#L8). Out of curiosity, in your ESM app startup, are you specifying the `--experimental-loader` flag _and_ including `-r newrelic`? I'm going to test that out on my end to see if it has an impact, but figured I'd ask you as well :)

**Comment by Marcholio** [comment]
Yes we have specified `--experimental-loader newrelic/esm-loader.mjs`, but not including `-r newrelic`.

**Comment by jmartin4563** [comment]
@Marcholio if you're unable to get a repro case, you could always go the self-service route of [enabling trace level agent logs](https://docs.newrelic.com/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration/#logging_config) in your actual app, and looking at the logs to see the naming being applied as the transaction is generated. Short of that, we would recommend that you engage our support so they can work with you to triage and if they're unable to pinpoint the root cause, provide that triage information to my team.

**Comment by bizob2828** [comment]
I'm going to close this. If you can get us a reproduction case, please reopen or continue to go the New Relic support route

**Comment by jordigh** [comment]
We have just been able to reproduce this case internally by using both the `newrelic.instrumentLoadedModule` API and the ESM loader at the same time. @Marcholio, were you also using both?

**Comment by Marcholio** [comment]
I don't think we are using `newrelic.instrumentLoadedModule` API.

**Comment by bizob2828** [comment]
I'm closing and will echo what @jmartin4563 said. @Marcholio if you're unable to get a repro case, you could always go the self-service route of [enabling trace level agent logs](https://docs.newrelic.com/docs/apm/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration/#logging_config) in your actual app, and looking at the logs to see the naming being applied as the transaction is generated. Short of that, we would recommend that you engage our support so they can work with you to triage and if they're unable to pinpoint the root cause, provide that triage information to my team.

**Comment by wiked03** [comment]
Hi Team,  I ran into this issue and created a repo with an example app to reproduce it.  The steps to reproduce are in the README

[Git Hub Repo](https://github.com/wiked03/newrelic-issue)

I originally posted my question on the Support Channel, so I will link to that here as a reference: 
https://forum.newrelic.com/s/hubtopic/aAX8W0000015BOiWAM/new-nodeexpress-app-shows-transaction-names-with-repeated-path-values

Let me know if there are any issues with the repo or if there are any additional questions.

Thanks!!

**Comment by jmartin4563** [comment]
Hiya @wiked03, thank you for the repro case! I'll be taking a look and will keep you posted on my findings

**Comment by jmartin4563** [comment]
@wiked03 confirmed that I'm able to repro with your example, digging into why the ESM loader seems to be registering instrumentation twice for express, will keep you posted

**Comment by jmartin4563** [comment]
@Marcholio and @wiked03, we've just published [v10.5.0](https://github.com/newrelic/node-newrelic/releases/tag/v10.5.0) with a fix for this issue, give it a try and let us know how it works for you both, sorry again for the inconvenience.

**Comment by wiked03** [comment]
> @Marcholio and @wiked03, we've just published [v10.5.0](https://github.com/newrelic/node-newrelic/releases/tag/v10.5.0) with a fix for this issue, give it a try and let us know how it works for you both, sorry again for the inconvenience.

Well, It's better, but not quite fixed.  It DOES report correctly for my simple example app, but the paths are still repeated in my real app.  However, they are repeated FEWER times than before.

Examples of before and after updating to 10.5 (the correct path is `/config`):
![image](https://github.com/newrelic/node-newrelic/assets/10564630/6a58537c-c9bf-4c53-8e7d-7f601ec95bd5)


I will try to update my example app to reproduce it and let you know.

**Comment by wiked03** [comment]
@jmartin4563   I was finally able to figure out why that fix did not work for my app.  It has something to do with swagger.  Just importing the `swagger-ui-express` library causes the path to be repeated in the APM.    Simply commenting out the import will fix it.

[Git Hub Repo](https://github.com/wiked03/newrelic-issue)

**Comment by jmartin4563** [comment]
@wiked03 confirmed that I'm able to reproduce with your app, working internally to come up with a solution, the change we made previously didn't go far enough in this case, will keep you posted.

**Comment by jmartin4563** [comment]
@wiked03 sorry for the delay but wanted to give you an update: the fix for this was a lot more involved than the previous change, and just wanted to let you know that we'll be shipping the fix in v11 of the agent (as it required us to make a breaking change). Thank you for your patience and help with resolving this issue!
